// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9zZcemTCBYW_WmfqxK7kzlwhvm7xYAOg',
    appId: '1:867516387230:web:efe2cd211d99090b45908f',
    messagingSenderId: '867516387230',
    projectId: 'vanrakshak-1db86',
    authDomain: 'vanrakshak-1db86.firebaseapp.com',
    storageBucket: 'vanrakshak-1db86.appspot.com',
    measurementId: 'G-ZN5G4GT1TT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDmDzGSLa0_bksyohgzX6O6WcPaX-e4os',
    appId: '1:867516387230:android:0ca3b324a11594e845908f',
    messagingSenderId: '867516387230',
    projectId: 'vanrakshak-1db86',
    storageBucket: 'vanrakshak-1db86.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfPMivfHfbdGwg3rPhH7u5LognRLILk8o',
    appId: '1:867516387230:ios:9a3d5cf8a1b0638b45908f',
    messagingSenderId: '867516387230',
    projectId: 'vanrakshak-1db86',
    storageBucket: 'vanrakshak-1db86.appspot.com',
    iosBundleId: 'com.example.vanrakshak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfPMivfHfbdGwg3rPhH7u5LognRLILk8o',
    appId: '1:867516387230:ios:4a095027de47f80445908f',
    messagingSenderId: '867516387230',
    projectId: 'vanrakshak-1db86',
    storageBucket: 'vanrakshak-1db86.appspot.com',
    iosBundleId: 'com.example.vanrakshak.RunnerTests',
  );
}
